In [56]:
import pandas as pd

In [57]:
path1 = '/Users/willmcdonald/Desktop/tablaeu challenge/data/JC-201910-citibike-tripdata.csv'
df_1 = pd.read_csv(path1)
df_1.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,892,2019-10-01 00:20:05.0140,2019-10-01 00:34:57.3800,3275,Columbus Drive,40.718355,-74.038914,3280,Astor Place,40.719282,-74.071262,29544,Subscriber,1976,1
1,374,2019-10-01 00:43:48.8790,2019-10-01 00:50:03.8190,3211,Newark Ave,40.721525,-74.046305,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,29536,Subscriber,1984,1
2,170,2019-10-01 01:35:51.8630,2019-10-01 01:38:42.5470,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,26304,Subscriber,1986,1
3,946,2019-10-01 02:55:53.4000,2019-10-01 03:11:40.2710,3272,Jersey & 3rd,40.723332,-74.045953,3679,Bergen Ave,40.722104,-74.071455,29496,Customer,1969,0
4,517,2019-10-01 03:10:16.1290,2019-10-01 03:18:53.6350,3206,Hilltop,40.731169,-74.057574,3210,Pershing Field,40.742677,-74.051789,26205,Subscriber,1969,1

In [58]:
path2 = '/Users/willmcdonald/Desktop/tablaeu challenge/data/JC-201911-citibike-tripdata.csv'
df_2 = pd.read_csv(path2)
df_2.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,260,2019-11-01 00:02:53.8860,2019-11-01 00:07:14.6450,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,26314,Subscriber,1964,1
1,285,2019-11-01 00:05:38.6360,2019-11-01 00:10:24.1930,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,26238,Subscriber,1986,2
2,501,2019-11-01 00:05:43.6310,2019-11-01 00:14:05.4810,3186,Grove St PATH,40.719586,-74.043117,3192,Liberty Light Rail,40.711242,-74.055701,29645,Subscriber,1995,1
3,556,2019-11-01 00:07:57.0550,2019-11-01 00:17:13.9010,3209,Brunswick St,40.724176,-74.050656,3678,Fairmount Ave,40.725726,-74.071959,29221,Customer,1992,1
4,321,2019-11-01 00:11:44.5660,2019-11-01 00:17:05.5930,3273,Manila & 1st,40.721651,-74.042884,3273,Manila & 1st,40.721651,-74.042884,29591,Subscriber,1988,1

In [59]:
path3 = '/Users/willmcdonald/Desktop/tablaeu challenge/data/JC-201912-citibike-tripdata.csv'
df_3 = pd.read_csv(path3)
df_3.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1553,2019-12-01 00:07:13.9360,2019-12-01 00:33:07.6820,3681,Grand St,40.715178,-74.037683,3198,Heights Elevator,40.748716,-74.040443,29462,Subscriber,1980,1
1,416,2019-12-01 00:16:40.4700,2019-12-01 00:23:36.5700,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29610,Subscriber,1956,1
2,294,2019-12-01 00:20:29.7980,2019-12-01 00:25:23.9690,3195,Sip Ave,40.730897,-74.063913,3678,Fairmount Ave,40.725726,-74.071959,26166,Subscriber,1977,1
3,97,2019-12-01 00:21:13.7580,2019-12-01 00:22:51.5970,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,29492,Subscriber,1993,1
4,286,2019-12-01 00:29:58.0230,2019-12-01 00:34:44.2280,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29440,Customer,1990,1

In [60]:
dfs= [df_1, df_2, df_3]
finaldf = pd.concat(dfs)
finaldf

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,892,2019-10-01 00:20:05.0140,2019-10-01 00:34:57.3800,3275,Columbus Drive,40.718355,-74.038914,3280,Astor Place,40.719282,-74.071262,29544,Subscriber,1976,1
1,374,2019-10-01 00:43:48.8790,2019-10-01 00:50:03.8190,3211,Newark Ave,40.721525,-74.046305,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,29536,Subscriber,1984,1
2,170,2019-10-01 01:35:51.8630,2019-10-01 01:38:42.5470,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,26304,Subscriber,1986,1
3,946,2019-10-01 02:55:53.4000,2019-10-01 03:11:40.2710,3272,Jersey & 3rd,40.723332,-74.045953,3679,Bergen Ave,40.722104,-74.071455,29496,Customer,1969,0
4,517,2019-10-01 03:10:16.1290,2019-10-01 03:18:53.6350,3206,Hilltop,40.731169,-74.057574,3210,Pershing Field,40.742677,-74.051789,26205,Subscriber,1969,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19723,283,2019-12-31 23:12:18.5480,2019-12-31 23:17:01.8740,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29245,Customer,1990,1
19724,267,2019-12-31 23:19:03.5840,2019-12-31 23:23:30.6640,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26153,Subscriber,1989,1
19725,379,2019-12-31 23:19:06.5830,2019-12-31 23:25:25.7970,3209,Brunswick St,40.724176,-74.050656,3185,City Hall,40.717733,-74.043845,26276,Subscriber,1984,1
19726,188,2019-12-31 23:24:00.2630,2019-12-31 23:27:09.0400,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,29461,Subscriber,1987,1
19727,326,2019-12-31 23:45:20.9780,2019-12-31 23:50:47.7490,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29123,Subscriber,1988,1

In [61]:
finaldf['tripduration']= finaldf['tripduration']/60

In [62]:
finaldf['tripduration'] = finaldf['tripduration'].round(2)
finaldf

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,14.87,2019-10-01 00:20:05.0140,2019-10-01 00:34:57.3800,3275,Columbus Drive,40.718355,-74.038914,3280,Astor Place,40.719282,-74.071262,29544,Subscriber,1976,1
1,6.23,2019-10-01 00:43:48.8790,2019-10-01 00:50:03.8190,3211,Newark Ave,40.721525,-74.046305,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,29536,Subscriber,1984,1
2,2.83,2019-10-01 01:35:51.8630,2019-10-01 01:38:42.5470,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,26304,Subscriber,1986,1
3,15.77,2019-10-01 02:55:53.4000,2019-10-01 03:11:40.2710,3272,Jersey & 3rd,40.723332,-74.045953,3679,Bergen Ave,40.722104,-74.071455,29496,Customer,1969,0
4,8.62,2019-10-01 03:10:16.1290,2019-10-01 03:18:53.6350,3206,Hilltop,40.731169,-74.057574,3210,Pershing Field,40.742677,-74.051789,26205,Subscriber,1969,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19723,4.72,2019-12-31 23:12:18.5480,2019-12-31 23:17:01.8740,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29245,Customer,1990,1
19724,4.45,2019-12-31 23:19:03.5840,2019-12-31 23:23:30.6640,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26153,Subscriber,1989,1
19725,6.32,2019-12-31 23:19:06.5830,2019-12-31 23:25:25.7970,3209,Brunswick St,40.724176,-74.050656,3185,City Hall,40.717733,-74.043845,26276,Subscriber,1984,1
19726,3.13,2019-12-31 23:24:00.2630,2019-12-31 23:27:09.0400,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,29461,Subscriber,1987,1
19727,5.43,2019-12-31 23:45:20.9780,2019-12-31 23:50:47.7490,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29123,Subscriber,1988,1

In [63]:
finaldf['gender']= finaldf['gender'].map({0: "Unknown", 1: "Male", 2: 'Female'})
finaldf

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,14.87,2019-10-01 00:20:05.0140,2019-10-01 00:34:57.3800,3275,Columbus Drive,40.718355,-74.038914,3280,Astor Place,40.719282,-74.071262,29544,Subscriber,1976,Male
1,6.23,2019-10-01 00:43:48.8790,2019-10-01 00:50:03.8190,3211,Newark Ave,40.721525,-74.046305,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,29536,Subscriber,1984,Male
2,2.83,2019-10-01 01:35:51.8630,2019-10-01 01:38:42.5470,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,26304,Subscriber,1986,Male
3,15.77,2019-10-01 02:55:53.4000,2019-10-01 03:11:40.2710,3272,Jersey & 3rd,40.723332,-74.045953,3679,Bergen Ave,40.722104,-74.071455,29496,Customer,1969,Unknown
4,8.62,2019-10-01 03:10:16.1290,2019-10-01 03:18:53.6350,3206,Hilltop,40.731169,-74.057574,3210,Pershing Field,40.742677,-74.051789,26205,Subscriber,1969,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19723,4.72,2019-12-31 23:12:18.5480,2019-12-31 23:17:01.8740,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29245,Customer,1990,Male
19724,4.45,2019-12-31 23:19:03.5840,2019-12-31 23:23:30.6640,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26153,Subscriber,1989,Male
19725,6.32,2019-12-31 23:19:06.5830,2019-12-31 23:25:25.7970,3209,Brunswick St,40.724176,-74.050656,3185,City Hall,40.717733,-74.043845,26276,Subscriber,1984,Male
19726,3.13,2019-12-31 23:24:00.2630,2019-12-31 23:27:09.0400,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,29461,Subscriber,1987,Male
19727,5.43,2019-12-31 23:45:20.9780,2019-12-31 23:50:47.7490,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29123,Subscriber,1988,Male

In [65]:
csvpath = '/Users/willmcdonald/Desktop/tablaeu challenge/data'
finaldf.to_csv('data/finaldata.csv', index=False)